Feature/10 array clean
ZWRKje/js-basic-hw pull request #10
Opened 2023-11-13 18:59 UTC by ZWRKje

2023-11-13 19:40 UTC, Levitinn requested changes

2023-11-14 16:07 UTC, ZWRKje commented on 10-array-clean/solution.js
Привет, вынес колбек в отдельную функцию.

2023-11-19 15:11 UTC, Levitinn reviewed
оставил вопрос в комментарии

2023-11-19 15:11 UTC, Levitinn commented on 10-array-clean/solution.js
> +    !cb(arr[i], i, arr) && newArr.push(arr[i]);
а зачем ты передаешь в cb три аргумента если функция isGreaterThree принимает только один?

2023-11-19 15:19 UTC, ZWRKje commented on 10-array-clean/solution.js
> +    !cb(arr[i], i, arr) && newArr.push(arr[i]);
Идея была в том, что бы написать что то похожее на Array.prototype.filter. Где коллбек вызывается с тремя аргументами. А так да, для функции isGreaterThree не нужны остальные аргументы.

2023-11-19 15:21 UTC, Levitinn commented on 10-array-clean/solution.js
> +    !cb(arr[i], i, arr) && newArr.push(arr[i]);
тогда исправь и отправляй) лишние аргументы введут в заблуждение других членов команды (если смотреть на рабочий процесс)

2023-11-28 16:19 UTC, merged